Fixes the fair sampling, but not entirely sure;
dkuska/hpi-adp-ind pull request #50
Opened 2023-02-14 21:51 UTC by yjojo17

Makes the Missing Value Parameter dependet on 50% of largest column.
And fixes the fair sampling but not sure if the logic is fault tolerant now, how I made it. Is not that easy to undestand what i do there so if you want to go over the PR just contact me.

2023-02-20 12:54 UTC, ClFeSc commented
> Is not that easy to undestand what i do there so if you want to go over the PR just contact me.

I agree with that. I haven't really understood it, so I'll look into it again later.

2023-02-28 19:04 UTC, ClFeSc reviewed
I've taken a deeper look, refactored the `missing_values` count a bit, and merged the current changes. Still have to understand the `assign_budget` method.

2023-02-28 19:04 UTC, ClFeSc commented on pysrc/models/metanome_run.py
> +        #TODO Probably need the value of the parameter also in the JSON output or?
I have refactored that.

2023-02-28 19:04 UTC, ClFeSc commented on pysrc/scripts/sampling.py
> +    if count_columns_not_full <= 1:
Just curious: Was this an actual problem?

2023-02-28 19:04 UTC, ClFeSc commented on pysrc/scripts/sampling.py
> +            track_changes = 0
Any particular reason for declaring this here, and not just passing a literal `0` to `assign_budget`?

2023-03-01 19:50 UTC, yjojo17 commented on pysrc/scripts/sampling.py
> +            track_changes = 0
nope don't think I have a reason for it will adapt this

2023-03-03 18:49 UTC, ClFeSc reviewed
I'm still not sure I understand everything, but it's much better now.

2023-03-03 18:49 UTC, ClFeSc commented on pysrc/scripts/sampling.py
> +                # it doesn't fit so far but the budget of this iteration is added to the basic size for the next iteration
I don't get this comment. `basic_size` is not even assigned in the next few lines which I'd have expected from `the budget of this iteration is added to the basic size for the next iteration`.

2023-03-03 18:49 UTC, ClFeSc commented on pysrc/scripts/sampling.py
> +                # decrease the budget pool by the now used budget
You say `decrease` here but `budget_to_share` will be larger after the `else`.

2023-03-06 18:40 UTC, ClFeSc reviewed
I think I'm starting to understand what you're doing. @dkuska What do you think about this?

2023-03-06 18:40 UTC, ClFeSc commented on pysrc/scripts/sampling.py
> +                    #size_for_column.allowed_budget = budget_per_column + basic_size
Is this line still relevant?

2023-03-09 11:48 UTC, ClFeSc commented
Was https://github.com/dkuska/hpi-adp-ind/pull/50/commits/20b59b44c40bee069a732f88d916f5c9260b538b intended by any means? It seems ... destructive.

2023-03-09 11:50 UTC, yjojo17 commented
> 

No my Version Control got messed up my VM died while pushing trying to resolve it currently

2023-03-09 11:55 UTC, yjojo17 commented
In FixFairSamplin2 is the corrected one

2023-03-09 11:57 UTC, yjojo17 commented
> 

Interestingly the commit before the destructive one had already all relevant changes not sure why git wasn't me allowing to only commit this ._.

2023-03-20 12:48 UTC, yjojo17 commented
Approve?

2023-03-31 11:08 UTC, ClFeSc requested changes
There are still at least four problems:

1. The budget is not used as efficiently as possible: In SCOP, there exists a distribution that uses 478 of the budget (7 and 11 for the columns that fit entirely and 23 for the rest). In case the total budget is at least 478 but not more than 483, this distribution is not chosen. Instead, 22 for all columns that don't fit is chosen. This is however not a large range where it is incorrect, and it stays under budget.
2. In SCOP, when the allowed budget is under 418, the budget is not respected and every column seems to be entirely taken. This is also not that bad as this only happens for small budgets.
3. When choosing a budget that is too large (e.g. 1 million for SCOP), I get a division by zero error.
4. There are still budgets where the distribution exceeds the budget, e.g. 500,000 for SCOP.

2023-03-31 13:19 UTC, yjojo17 commented
> 

1. is probably caused thgrough math.floor in calculations of the budgets 
2. hit a break condition that shouldn't be hit is fixed now
3. is fixed missed to a push a local commit therere
4.  is also fixed i returned to much budget to the pool in the recursive calling of the function.

2023-03-31 17:47 UTC, ClFeSc approved these changes
New changes seem to be working.

There is still the issue that in some cases there might be a more efficient way of assigning budget, but what I could find were only very small deviations, so from my point of view it's fine.

Also, there are some code-style imperfections in the latest commit, but I'd be fine with keeping them for the sake of getting this ready.

2023-03-31 21:00 UTC, merged